version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name main --jetstream --http_port 8222"
  
  api:
   image: api
   build:
     context: .
     dockerfile: ./Dockerfiles/api
   ports:
     - "6660:6660"
   depends_on: ["nats"]
   environment:
    - NATS_HOST=nats
    - RUST_LOG=info
  
  spot-finder:
   image: spot-finder
   build:
     context: .
     dockerfile: ./Dockerfiles/spot-finder
   depends_on: ["nats"]
   environment:
    - NATS_HOST=nats
    - RUST_LOG=info

  horizon-service:
   image: horizon-service
   build:
     context: .
     dockerfile: ./Dockerfiles/horizon-service
   depends_on: ["nats"]
   environment:
    - NATS_HOST=nats
  
  sky-service:
   image: sky-service
   build:
     context: .
     dockerfile: ./Dockerfiles/sky-service
   depends_on: ["nats"]
   environment:
    - NATS_HOST=nats
    - RUST_LOG=info
