on:
  push:
    branches:
      - latest

enable-email-notifications: true

jobs:
  build-and-test:
    runs-on: dagger
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build and test backend
        run: dagger call build-and-test-backend

  publish-and-deploy:
    runs-on: dagger

    needs:
      - build-and-test

    if: forge.ref_name == 'latest'

    steps:
      - uses: actions/checkout@v7

      - name: Publish backend images
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          set -x

          dagger call publish-images \
            --tag ${{ forge.ref_name }} \
            --actor ${{ forge.actor }} \
            --token env://ACCESS_TOKEN

      - name: Deploy backend on kusomiso
        env:
          KUSOMISO_KEY: ${{ secrets.KUSOMISO_KEY }}
        run: |
          set -x
      
          dagger call deploy-backend \
            --host ${{ secrets.KUSOMISO_HOST }} \
            --user ${{ secrets.KUSOMISO_USER }} \
            --key env://KUSOMISO_KEY
