on: [push]

enable-email-notifications: true

jobs:
  build-frontend:
    runs-on: dagger
    steps:
      - uses: actions/checkout@v6

      - name: Build frontend
        run: dagger call build-frontend

  deploy-frontend:
    runs-on: dagger

    needs:
      - build-frontend

    if: forge.ref_name == 'latest'

    steps:
      - uses: actions/checkout@v6

      - name: Deploy frontend
        env:
          TOKEN: ${{ forge.token }}
        run: dagger call deploy-frontend --token env://TOKEN

