on: [push]

jobs:
  build-frontend:
    runs-on: dagger
    steps:
      - uses: actions/checkout@v6

      - name: Build frontend
        run: dagger call build-frontend

  deploy-frontend:
    runs-on: dagger

    needs:
      - build-frontend

    if: forge.ref_name == 'forgejo-workflows' # TODO: switch to latest branch

    steps:
      - uses: actions/checkout@v6

      - name: Build frontend
        run: |
          set -x

          mkdir ./frontend-dist
          dagger call build-frontend export --path ./frontend-dist

      - name: Debug
        run: |
          touch test-file
          ls -la
          chmod 755 ./frontend-dist

      - uses: actions/git-pages@v2
        with:
          site: https://sunn.cloudsftp.de/
          server: pages.energiesandsuch.com
          token: ${{ forge.token }}
          source: ./frontend-dist
