name: Update dependencies

on:
  push:
    branches:
      - "renovate/configure"
  schedule:
    - cron: "40 * * * *"
  workflow_dispatch:

enable-email-notifications: true

jobs:
  run-renovate:
    runs-on: dagger
    steps:
      - name: Run renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
        run: |
          set -x

          dagger \
            -m https://codeberg.org/clouds666/daggerverse/renovate@latest \
              --languages go,cargo,bun \
            call run \
              --renovate-token env://RENOVATE_TOKEN \
              --github-com-token env://GITHUB_COM_TOKEN \
              --repositories \
              "${{ forge.repository }},${{ forge.repository_owner }}/horizon"
