[package]
name = "spot-finder"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
async-nats = "0.29.0"
bytes = "1.4.0"
futures-util = "0.3.28"
osm-xml = "0.6.2"
reqwest = "0.11.16"
serde = "1.0.160"
serde_json = "1.0.96"
tokio = { version = "1.27.0", features = ["rt-multi-thread"] }
messages-common = { git = "http://github.com/sunangel-project/messages-common.git", version = "0.1.2" }
