[package]
name = "spot-finder"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-nats = "0.29.0"
bytes = "1.4.0"
futures-util = "0.3.28"
osm-xml = "0.6.2"
reqwest = "0.11.17"
serde = "1.0.162"
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["rt-multi-thread"] }
messages-common = { path = "../messages-common" }
log = "0.4.17"
env_logger = "0.10.0"
