[package]
name = "spot-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
messages-common = { workspace = true }
version-common = { workspace = true }

anyhow = { workspace = true }
async-nats = { workspace = true }
bytes = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

osm-xml = "0.6.2"
geoutils = "0.5.1"
