[package]
name = "sky-service"
version = "0.1.0"
edition = "2024"

[dependencies]
messages-common = { path = "../messages-common" }
version-common = { path = "../version-common" }

anyhow = { workspace = true }
async-nats = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

thiserror = "2.0.20"
