[package]
name = "sky-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-nats = "0.29.0"
chrono = { version = "0.4.26", features = ["serde"] }
env_logger = "0.10.0"
futures-util = "0.3.28"
log = "0.4.19"
messages-common = { path = "../messages-common" }
serde = "1.0.178"
serde_json = "1.0.104"
spa = "0.4.0"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["rt-multi-thread"] }
