[package]
name = "api"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
juniper = "0.15.11"
warp = "0.3.5"
juniper_warp = { version = "0.7.0", features = ["subscriptions"] }
juniper_graphql_ws = "0.3.0"
chrono = { version = "0.4.24", features = ["serde"] }
async-nats = "0.29.0"
futures-util = "0.3.28"
serde = "1.0.162"
serde_json = "1.0.96"
uuid = { version = "1.3.2", features = ["v4"] }
messages-common = { path = "../messages-common" }
futures = "0.3.28"
log = "0.4.17"
anyhow = "1.0.71"
bytes = "1.4.0"
env_logger = "0.10.0"
async-stream = "0.3.5"

