[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
messages-common = { workspace = true }
version-common = { workspace = true }

anyhow = { workspace = true }
async-nats = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

actix-web = { version = "4.14.0", features = ["openssl"] }
actix-cors = "0.7.1"
juniper = { version = "0.17.1", features = ["chrono", "chrono-tz"] }
juniper_graphql_ws = "0.5.0"
juniper_actix = { version = "0.7.0", features = ["subscriptions"] }

async-stream = "0.3.6"
openssl = "0.10.81"
uuid = { version = "1.23.4", features = ["v4"] }

