[package]
name = "api"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#juniper = { path = "../../juniper/juniper", features = ["chrono"] }
#juniper_graphql_ws = { path = "../../juniper/juniper_graphql_ws" }
#juniper_actix = { path = "../../juniper/juniper_actix", features = ["subscriptions"] }
juniper = { git = "https://github.com/graphql-rust/juniper", branch="master", features = ["chrono"] }
juniper_graphql_ws = {git = "https://github.com/graphql-rust/juniper", branch="master" }
juniper_actix = { git = "https://github.com/graphql-rust/juniper", branch="master",  features = ["subscriptions"] }
# TODO: revert juniper back to official version when 0.16 released

actix-web = "4.3.1"
actix-cors = "0.6.4"
chrono = { version = "0.4.26", features = ["serde"] }
async-nats = "0.29.0"
futures-util = "0.3.28"
serde = "1.0.170"
serde_json = "1.0.100"
uuid = { version = "1.4.0", features = ["v4"] }
messages-common = { path = "../messages-common" }
futures = "0.3.28"
log = "0.4.19"
anyhow = "1.0.71"
bytes = "1.4.0"
env_logger = "0.10.0"
async-stream = "0.3.5"

