name: Build, publish and deploy backend

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    env:
      CLOUDSFTP_CERT: ${{ secrets.CLOUDSFTP_CERT }}
      CLOUDSFTP_CERT_KEY: ${{ secrets.CLOUDSFTP_CERT_KEY }}

    steps:
      - uses: actions/checkout@v4

        # Build and push

      - name: Build images
        run: ./scripts/build_images.sh

      - name: Push images
        run: ./scripts/push_images.sh "${{ github.ref_name }}" "${{ github.actor }}" "${{ github.token }}"

        # Deploy

      - name: Deploy backend on kusomiso
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.KUSOMISO_HOST }}
          username: ${{ secrets.KUSOMISO_USERNAME }}
          key: ${{ secrets.KUSOMISO_SSH_KEY }}
          script: ./deploy.sh
