name: Build and publish docker images

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      CLOUDSFTP_CERT: ${{ secrets.CLOUDSFTP_CERT }}
      CLOUDSFTP_CERT_KEY: ${{ secrets.CLOUDSFTP_CERT_KEY }}
    steps:
      - uses: actions/checkout@v4

        # Build and push

      - name: Build images
        run: ./scripts/build_images.sh

      - name: Push images
        run: ./scripts/push_images.sh "${{ github.ref_name }}" "${{ github.actor }}" "${{ github.token }}"

        # Deploy

      - name: Deploy backend on kusomiso
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.KUSOMISO_HOST }}
          username: ${{ secrets.KUSOMISO_USERNAME }}
          key: ${{ secrets.KUSOMISO_SSH_KEY }}
          script: ./deploy.sh

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: |
          cd front
          npm ci

      - name: Deploy frontend on github-pages
        run: |
          cd front
          ./deploy.sh
