name: Build and publish docker images

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      CLOUDSFTP_CERT: ${{ secrets.CLOUDSFTP_CERT }}
      CLOUDSFTP_CERT_KEY: ${{ secrets.CLOUDSFTP_CERT_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: ./scripts/build_images.sh

      - name: Push images
        run: ./scripts/push_images.sh "${{ github.ref_name }}" "${{ github.actor }}" "${{ github.token }}"
