name: Build and deploy frontend

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Build frontend
        run: |
          cd front
          npm ci
          npm run build

      - uses: actions/upload-pages-artifact@3
        with:
          path: ./front/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
