name: Build, Test, and Deploy

on: [push, pull_request]

jobs:
  build_and_test_backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build and Test All
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "latest"
          verb: call
          args: build-and-test-backend
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  publish_and_deploy_backend:
    name: Publish and Deploy Backend
    runs-on: ubuntu-latest

    needs:
      - build_and_test_backend

    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v6

      - name: Publish Backend Images
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "latest"
          verb: call
          args: publish-images --version=$VERSION --actor=$GITHUB_ACTOR --token=env:GITHUB_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          VERSION: ${{ github.ref_name }}

      - name: Deploy backend on kusomiso
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.KUSOMISO_HOST }}
          username: ${{ secrets.KUSOMISO_USERNAME }}
          key: ${{ secrets.KUSOMISO_SSH_KEY }}
          script: ./deploy.sh

  build_and_test_frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Build frontend
        run: |
          cd front
          bun ci
          bun run build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./front/dist

  deploy_frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    needs:
      - build_and_test_frontend

    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
