name: Build and Test

on: push

jobs:
  build_and_test:
    name: Build and Test All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Test All
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: pipeline --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  publish_and_deploy:
    name: Publish and Deploy
    runs-on: ubuntu-latest

    needs:
      - build_and_test

    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
      - name: Publish Images
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: publish-images --source=. --version=$VERSION --actor=$GITHUB_ACTOR --token=env:GITHUB_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          VERSION: ${{ github.ref_name }}

      #- name: Deploy
      #  uses: dagger/dagger-for-github@v6
      #  with:
      #    version: "latest"
      #    verb: call
      #    args: deploy --source=. --host=env:HOST --username=env:USERNAME --key=env:KEY
      #    cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      #  env:
      #    HOST: ${{ secrets.KUSOMISO_HOST }}
      #    USERNAME: ${{ secrets.KUSOMISO_USERNAME }}
      #    KEY: ${{ secrets.KUSOMISO_SSH_KEY }}

      - name: Deploy backend on kusomiso
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.KUSOMISO_HOST }}
          username: ${{ secrets.KUSOMISO_USERNAME }}
          key: ${{ secrets.KUSOMISO_SSH_KEY }}
          script: ./deploy.sh
